using PBL3.Model.Bean;
using PBL3.Model.Dao;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Windows.Forms;

namespace PBL3.Models.Bo
{
    public class Bo_StaffModel
    {
        private Dao_StaffModel daoStaff;

        public Bo_StaffModel()
        {
            daoStaff = new Dao_StaffModel();
        }
        // Lấy danh sách tất cả nhân viên
        public List<StaffModel> GetAllStaff()
        {
            return daoStaff.GetAllStaff();
        }

        // Thêm nhân viên mới với tự sinh StaffID
        public bool AddStaffWithAutoGeneratedID(StaffModel staff)
        {
            return daoStaff.AddStaffWithAutoGeneratedID(staff);
        }

        // Cập nhật thông tin nhân viên
        public bool UpdateStaff(StaffModel staff)
        {
            return daoStaff.UpdateStaff(staff);
        }

        // Xóa nhân viên
        public bool DeleteStaff(string userID)
        {
            return daoStaff.DeleteStaff(userID);
        }
        public bool DeleteStaffByUserID(int _userID)
        {
            return daoStaff.DeleteStaffByUserID(_userID);
        }
        // Tìm kiếm nhân viên
        public List<StaffModel> SearchStaff(string searchBy, string searchValue)
        {
            return daoStaff.SearchStaff(searchBy, searchValue);
        }
        public Dictionary<string, int> GetStaffCountByMonth()
        {
            return daoStaff.GetStaffCountByMonth();
        }
        public int GetTotalStaffCount()
        {
            if (daoStaff != null)
            {
                return daoStaff.GetTotalStaffCount();
            }
            else
            {
                // Handle the case where daoStaffModel is null
                return 0; // Or throw an exception, depending on your requirements
            }
        }

    }
}
